workspace = { members = ["forward-list"] }
[package]
name = "linked-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
forward-list = { path = "forward-list", version = "0.1.0" }
